[package]
name = "setbits"
version = "0.1.0"
rust-version = "1.78.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/Oakchris1955/setbits-rs"
exclude = [".github/"]

[dependencies]
akin = "0.4.0"

[features]
default = ["inline"]
inline = []
